## Generated by bootstrap-modules.
## Do not edit by hand.

$(srcdir)/modules-bootstrap.stamp: $(boostrap_modules_deps)
	baux=$$(cd $(top_srcdir)/build-aux && pwd);     \
	  cd $(top_srcdir)/modules/ &&                  \
	  $$baux/bin/bootstrap-modules 'modules/'
	echo "$$(date): $?" >>$@

EXTRA_DIST +=                                   \
  $(srcdir)/modules-bootstrap.stamp            \
  $(srcdir)/modules.ac                         \
  $(srcdir)/modules.mk

$(srcdir)/modules.ac: $(srcdir)/modules-bootstrap.stamp
$(srcdir)/modules.mk: $(srcdir)/modules-bootstrap.stamp

# Automake uses the name $(top_srcdir) to qualify configure.ac.  The
# other targets are qualified with $(srcdir).
$(top_srcdir)/configure.ac: $(srcdir)/modules.ac
EXTRA_DIST += system/ros/module.ac
EXTRA_DIST += system/ros/module.ac.auto
include system/ros/module.mk
EXTRA_DIST += algorithm/md5/module.ac
EXTRA_DIST += algorithm/md5/module.ac.auto
include algorithm/md5/module.mk.auto

boostrap_modules_deps = \
  $(top_srcdir)/build-aux/bin/bootstrap-modules	\
  $(srcdir)/algorithm/md5/module.ac	\
  $(srcdir)/algorithm/md5/module.ac.auto	\
  $(srcdir)/system/ros/module.ac	\
  $(srcdir)/system/ros/module.ac.auto
