AST_NODES =  \
  ast/and.hh ast/and.hxx ast/and.cc  \
  ast/assign.hh ast/assign.hxx ast/assign.cc  \
  ast/assignment.hh ast/assignment.hxx ast/assignment.cc  \
  ast/ast.hh ast/ast.hxx ast/ast.cc  \
  ast/at.hh ast/at.hxx ast/at.cc  \
  ast/binding.hh ast/binding.hxx ast/binding.cc  \
  ast/break.hh ast/break.hxx ast/break.cc  \
  ast/call.hh ast/call.hxx ast/call.cc  \
  ast/call-msg.hh ast/call-msg.hxx ast/call-msg.cc  \
  ast/catch.hh ast/catch.hxx ast/catch.cc  \
  ast/class.hh ast/class.hxx ast/class.cc  \
  ast/composite.hh ast/composite.hxx ast/composite.cc  \
  ast/continue.hh ast/continue.hxx ast/continue.cc  \
  ast/declaration.hh ast/declaration.hxx ast/declaration.cc  \
  ast/decrementation.hh ast/decrementation.hxx ast/decrementation.cc  \
  ast/dictionary.hh ast/dictionary.hxx ast/dictionary.cc  \
  ast/do.hh ast/do.hxx ast/do.cc  \
  ast/emit.hh ast/emit.hxx ast/emit.cc  \
  ast/event.hh ast/event.hxx ast/event.cc  \
  ast/exp.hh ast/exp.hxx ast/exp.cc  \
  ast/finally.hh ast/finally.hxx ast/finally.cc  \
  ast/flavored.hh ast/flavored.hxx ast/flavored.cc  \
  ast/float.hh ast/float.hxx ast/float.cc  \
  ast/foreach.hh ast/foreach.hxx ast/foreach.cc  \
  ast/if.hh ast/if.hxx ast/if.cc  \
  ast/implicit.hh ast/implicit.hxx ast/implicit.cc  \
  ast/incrementation.hh ast/incrementation.hxx ast/incrementation.cc  \
  ast/lvalue.hh ast/lvalue.hxx ast/lvalue.cc  \
  ast/lvalue-args.hh ast/lvalue-args.hxx ast/lvalue-args.cc  \
  ast/list.hh ast/list.hxx ast/list.cc  \
  ast/local.hh ast/local.hxx ast/local.cc  \
  ast/local-assignment.hh ast/local-assignment.hxx ast/local-assignment.cc  \
  ast/local-declaration.hh ast/local-declaration.hxx ast/local-declaration.cc  \
  ast/local-write.hh ast/local-write.hxx ast/local-write.cc  \
  ast/match.hh ast/match.hxx ast/match.cc  \
  ast/message.hh ast/message.hxx ast/message.cc  \
  ast/meta-args.hh ast/meta-args.hxx ast/meta-args.cc  \
  ast/meta-call.hh ast/meta-call.hxx ast/meta-call.cc  \
  ast/meta-exp.hh ast/meta-exp.hxx ast/meta-exp.cc  \
  ast/meta-id.hh ast/meta-id.hxx ast/meta-id.cc  \
  ast/meta-lvalue.hh ast/meta-lvalue.hxx ast/meta-lvalue.cc  \
  ast/nary.hh ast/nary.hxx ast/nary.cc  \
  ast/noop.hh ast/noop.hxx ast/noop.cc  \
  ast/op-assignment.hh ast/op-assignment.hxx ast/op-assignment.cc  \
  ast/pipe.hh ast/pipe.hxx ast/pipe.cc  \
  ast/property.hh ast/property.hxx ast/property.cc  \
  ast/property-action.hh ast/property-action.hxx ast/property-action.cc  \
  ast/property-write.hh ast/property-write.hxx ast/property-write.cc  \
  ast/return.hh ast/return.hxx ast/return.cc  \
  ast/routine.hh ast/routine.hxx ast/routine.cc  \
  ast/scope.hh ast/scope.hxx ast/scope.cc  \
  ast/stmt.hh ast/stmt.hxx ast/stmt.cc  \
  ast/string.hh ast/string.hxx ast/string.cc  \
  ast/subscript.hh ast/subscript.hxx ast/subscript.cc  \
  ast/tagged-stmt.hh ast/tagged-stmt.hxx ast/tagged-stmt.cc  \
  ast/this.hh ast/this.hxx ast/this.cc  \
  ast/throw.hh ast/throw.hxx ast/throw.cc  \
  ast/try.hh ast/try.hxx ast/try.cc  \
  ast/unary.hh ast/unary.hxx ast/unary.cc  \
  ast/unscope.hh ast/unscope.hxx ast/unscope.cc  \
  ast/while.hh ast/while.hxx ast/while.cc  \
  ast/write.hh ast/write.hxx ast/write.cc
